
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Release.Name}}-nginx-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  rules:
    - host: vetec.plate.team
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vetec-enms-service
                port:
                  number: 3722
    - host: hubis.plate.team
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hubis-enms-service
                port:
                  number: 3722
  tls:
    - hosts:
        - vetec.plate.team
      secretName: vetec-plateteam-tls
    - hosts:
        - hubis.plate.team
      secretName: hubis-plateteam-tls